export const TRACK_LAYOUT_OPTIONS = [
  { id: "bg",           label: "Neon Finish",        source: require("@/assets/images/bg.png") },
  { id: "bg1",          label: "Arcade Track",        source: require("@/assets/images/bg1.png") },
  { id: "galaxy",       label: "Galaxy",              source: require("@/assets/images/galaxy.jpeg") },
  { id: "daylightStadium", label: "Daylight Stadium", source: require("@/assets/images/daylightStadium.jpeg") },
  { id: "forest",       label: "Forest",              source: require("@/assets/images/forest.jpeg") },
  { id: "city",         label: "City",                source: require("@/assets/images/city.jpeg") },
  { id: "lava",         label: "Lava",                source: require("@/assets/images/lava.jpeg") },
  { id: "ice",          label: "Ice",                 source: require("@/assets/images/ice.jpeg") },
  { id: "candy",        label: "Candy Land",          source: require("@/assets/images/candy.jpeg") },
  { id: "farm",         label: "Farm",                source: require("@/assets/images/farm.jpeg") },
  { id: "underwater",   label: "Underwater",          source: require("@/assets/images/underwater.jpeg") },
  { id: "musicfest",    label: "Music Fest",          source: require("@/assets/images/musicfest.jpeg") },
  { id: "barbie",       label: "Barbie",              source: require("@/assets/images/track_barbie.png") },
  { id: "desert",       label: "Desert",              source: require("@/assets/images/track_desert.png") },
  { id: "gold",         label: "Gold",                source: require("@/assets/images/track_gold.png") },
  { id: "nightforest",  label: "Night Forest",        source: require("@/assets/images/track_nightforest.png") },
  { id: "skykingdom",   label: "Sky Kingdom",         source: require("@/assets/images/track_skykingdom.png") },
  { id: "rain",         label: "Rain",                source: require("@/assets/images/track_rain.png") },
  { id: "storm",        label: "Storm",               source: require("@/assets/images/track_storm.png") },
  { id: "mountain",     label: "Mountain",            source: require("@/assets/images/track_mountain.png") },
  { id: "waterfall",    label: "Waterfall",           source: require("@/assets/images/track_waterfall.png") },
  { id: "webcity",      label: "Web City",            source: require("@/assets/images/track_webcity.png") },
  { id: "bridge",       label: "Bridge",              source: require("@/assets/images/track_bridge.png") },
  { id: "newyork",      label: "New York",            source: require("@/assets/images/track_newyork.png") },
  { id: "pirateisland", label: "Pirate Island",       source: require("@/assets/images/track_pirateisland.png") },
  { id: "paradise",     label: "Paradise",            source: require("@/assets/images/track_paradise.png") },
  { id: "musicfest2",   label: "Music Fest 2",        source: require("@/assets/images/track_musicfest2.png") },
  { id: "chocolate",    label: "Chocolate Factory",   source: require("@/assets/images/track_chocolate.png") },
  { id: "fireworks",    label: "Fireworks",           source: require("@/assets/images/track_fireworks.png") },
  { id: "moon",         label: "Moon Base",           source: require("@/assets/images/track_moon.png") },
  { id: "rainbow_road", label: "Rainbow Road",        source: require("@/assets/images/track_rainbow_road.png") },
  { id: "runway",       label: "Runway",              source: require("@/assets/images/track_runway.png") },
  { id: "toy_race",     label: "Toy Race",            source: require("@/assets/images/track_toy_race.png") },
  { id: "water_park",   label: "Water Park",          source: require("@/assets/images/track_water_park.png") },
] as const;

export type TrackLayoutId = (typeof TRACK_LAYOUT_OPTIONS)[number]["id"];

export const FREE_TRACK_CODES = new Set<string>(["bg", "daylightStadium"]);
