export type FaqItem = {
  q: string;
  a: string;
};

export type FaqSection = {
  title: string;
  items: FaqItem[];
};

/** Canonical Walk Champ FAQ — used by Profile FAQ screen and My Profile FAQ subpage. */
export const WALK_CHAMP_FAQ: FaqSection[] = [
  {
    title: "Getting Started",
    items: [
      {
        q: "What is Walk Champ?",
        a: [
          "Walk Champ is a competitive walking and fitness app where users track verified steps, join challenges, race against other participants, climb leaderboards, earn coins and achievements, and compete for eligible rewards.",
          "",
          "Depending on availability in your region, you can participate in:",
          "• Free Challenges",
          "• Coins Battles",
          "• Cash Prize Challenges",
          "• Sponsored Events",
          "• Public and private rooms",
          "• Scheduled races",
          "• Groups and group competitions",
          "",
          "Your progress is based on step data received through Apple Health on iOS or Health Connect on Android.",
        ].join("\n"),
      },
      {
        q: "What do I need to use Walk Champ?",
        a: [
          "You need:",
          "• A supported Android phone or iPhone",
          "• Apple Health on iOS or Health Connect on Android",
          "• Permission for Walk Champ to read step information",
          "• An internet connection for registration, live updates, chat, notifications, and payments",
          "• A supported account and region for paid Cash Prize Challenges",
          "",
          "A smartwatch is optional. Any compatible wearable must sync its step data to Apple Health or Health Connect.",
        ].join("\n"),
      },
      {
        q: "Does Walk Champ count steps by itself?",
        a: [
          "Walk Champ does not rely only on an internal pedometer.",
          "",
          "On iPhone, Walk Champ reads your permitted step records from Apple Health.",
          "",
          "On Android, Walk Champ reads your permitted step records from Health Connect.",
          "",
          "This provides a consistent source for verifying step activity across supported phones and wearables.",
        ].join("\n"),
      },
      {
        q: "Is Walk Champ a gambling app?",
        a: [
          "Walk Champ challenges are designed as skill-based walking competitions. Results are determined by verified physical activity, step progress, completion time, and challenge rules—not by random outcomes.",
          "",
          "Cash Prize Challenges may not be available in every country or US state. Access depends on your age, account status, current location, applicable laws, and Walk Champ’s regional configuration.",
          "",
          "Users should participate responsibly and enter only amounts they are comfortable spending.",
        ].join("\n"),
      },
      {
        q: "Who can use Walk Champ?",
        a: [
          "Supported users can access general fitness, Free Challenge, Coins, Groups, leaderboard, and social features.",
          "",
          "Cash Prize Challenges may require:",
          "• A minimum age of 18",
          "• A supported country or US state",
          "• Location verification",
          "• Identity or KYC verification",
          "• An eligible payment and payout method",
          "• Acceptance of the applicable challenge terms",
          "",
          "Walk Champ may disable paid features where they are not permitted or supported.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Step Tracking",
    items: [
      {
        q: "How does Walk Champ track my steps?",
        a: [
          "Walk Champ reads step records from:",
          "• Apple Health on iOS",
          "• Health Connect on Android",
          "",
          "The Walk screen may show your total daily steps, while a live challenge shows only the steps recorded during that race’s eligible time period.",
        ].join("\n"),
      },
      {
        q: "How do I connect Apple Health?",
        a: [
          "Open your Walk Champ profile and select Set Up Step Tracking.",
          "",
          "Allow Walk Champ to read your step information. If permission was previously denied, review the Health permissions in your iPhone settings or Apple Health, then return to Walk Champ and try again.",
        ].join("\n"),
      },
      {
        q: "How do I connect Health Connect?",
        a: [
          "Open your Walk Champ profile and select Set Up Step Tracking.",
          "",
          "Install or open Health Connect when prompted, grant the required step permissions, and return to Walk Champ. Tap Try Again if the connection does not refresh automatically.",
          "",
          "Your phone or wearable’s companion app must also write step records into Health Connect.",
        ].join("\n"),
      },
      {
        q: "What is the most reliable way to record steps?",
        a: [
          "For reliable tracking:",
          "• Keep your phone with you while walking, or use a supported wearable.",
          "• Confirm the wearable is syncing to Apple Health or Health Connect.",
          "• Keep health permissions enabled.",
          "• Open Walk Champ periodically during long challenges.",
          "• Check your race progress before the challenge ends.",
          "• Keep your phone and wearable charged.",
        ].join("\n"),
      },
      {
        q: "Can I use an Apple Watch, Fitbit, Garmin, Oura, or WHOOP?",
        a: [
          "A wearable may work when its companion app successfully writes step records into Apple Health or Health Connect.",
          "",
          "Walk Champ does not necessarily read information directly from the wearable’s own app. Sync quality and timing depend on the wearable, its companion app, and the connected health platform.",
        ].join("\n"),
      },
      {
        q: "Why is my wearable’s count different from Walk Champ?",
        a: [
          "Your wearable app may display its own raw step count, while Apple Health or Health Connect may merge, prioritize, delay, filter, or remove duplicate records from multiple sources.",
          "",
          "Walk Champ uses the supported health platform as its source. Compare Walk Champ with Apple Health or Health Connect rather than only comparing it with the wearable’s own app.",
        ].join("\n"),
      },
      {
        q: "Do I need to carry my phone?",
        a: [
          "Not necessarily, provided a supported wearable is recording your steps and syncing them correctly.",
          "",
          "If neither your phone nor a wearable records the activity, Walk Champ cannot count those steps.",
        ].join("\n"),
      },
      {
        q: "Who is responsible for making sure steps are recorded?",
        a: [
          "Users are responsible for:",
          "• Carrying or wearing a tracking device",
          "• Keeping the device charged",
          "• Maintaining health permissions",
          "• Confirming synchronization",
          "• Checking progress before the race ends",
          "",
          "Walk Champ cannot always recover activity that was never recorded by Apple Health or Health Connect.",
        ].join("\n"),
      },
      {
        q: "Do manually entered steps count?",
        a: [
          "No. Manually entered, altered, or suspicious step records are not eligible for Walk Champ races.",
          "",
          "Attempting to inflate activity can lead to:",
          "• Step removal",
          "• Disqualification",
          "• Prize forfeiture",
          "• Suspension",
          "• Permanent account closure",
          "",
          "Only genuine sensor-recorded activity should be used.",
        ].join("\n"),
      },
      {
        q: "Can I change devices during a challenge?",
        a: [
          "Yes. You can switch from a phone to a supported wearable, or between supported devices, as long as valid records continue to sync through Apple Health or Health Connect.",
          "",
          "Steps that were never recorded or never synchronized may not be recoverable later.",
        ].join("\n"),
      },
      {
        q: "Why are my steps missing or delayed?",
        a: [
          "First check:",
          "1. Walk Champ has health permission.",
          "2. Your steps appear in Apple Health or Health Connect.",
          "3. Your wearable’s companion app has synchronized.",
          "4. Battery-saving settings are not blocking background activity.",
          "5. Your phone has internet access.",
          "6. Your timezone is correct.",
          "",
          "Then reopen Walk Champ and refresh the screen.",
          "",
          "If the issue continues, contact admin@miragaming.com with screenshots, device details, race ID, and the approximate time of the issue.",
        ].join("\n"),
      },
      {
        q: "What should I do if I reached the goal but Walk Champ shows fewer steps?",
        a: [
          "Compare your health-platform records with the exact race start and end time.",
          "",
          "Check:",
          "• Race start time",
          "• Race end time",
          "• Current timezone",
          "• Apple Health or Health Connect records",
          "• Whether the activity synchronized before the race ended",
          "",
          "Contact admin@miragaming.com before results are finalized when possible. Walk Champ can review technical discrepancies but cannot create steps that never reached the health platform.",
        ].join("\n"),
      },
      {
        q: "What happens when I travel to another timezone?",
        a: [
          "Walk Champ stores scheduled times consistently and displays them using the applicable local timezone.",
          "",
          "When traveling:",
          "• Verify the displayed race start and end times.",
          "• Keep timezone synchronization enabled.",
          "• Confirm your device time is set automatically.",
          "• Refresh Walk Champ after arriving in the new timezone.",
          "",
          "Paid challenge availability may also depend on your current location.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Challenge Types",
    items: [
      {
        q: "What types of challenges are available?",
        a: [
          "Walk Champ supports several challenge types.",
          "",
          "Free Challenges have no cash or coin entry fee.",
          "",
          "Coins Battles require an in-app coin entry and provide a coin prize pool.",
          "",
          "Cash Prize Challenges require an eligible cash entry and award cash prizes according to the displayed payout structure.",
          "",
          "Sponsored Events are organized or funded by Walk Champ or a sponsor and may offer coins, cash, badges, recognition, or other configured rewards.",
          "",
          "Challenges can also be public, private, immediate, or scheduled for a future date.",
        ].join("\n"),
      },
      {
        q: "How do Free Challenges work?",
        a: [
          "Free Challenges do not require an entry payment.",
          "",
          "Users compete using verified steps and may earn:",
          "• Rankings",
          "• Coins",
          "• Achievement badges",
          "• Titles",
          "• Event-specific rewards",
          "",
          "The exact reward is displayed on the challenge card or details screen.",
        ].join("\n"),
      },
      {
        q: "Can a Free Challenge award coins or badges?",
        a: [
          "Yes. A Free Challenge may offer coins, badges, achievements, titles, or ranking recognition when configured.",
          "",
          "The card should display the actual reward. Walk Champ does not use negative descriptions such as “No cash prize.”",
        ].join("\n"),
      },
      {
        q: "How do Coins Battles work?",
        a: [
          "A Coins Battle requires the displayed number of Walk Champ coins to enter.",
          "",
          "The card shows:",
          "• Coin entry amount",
          "• Step goal",
          "• Current participant count",
          "• Coin prize pool",
          "• Scheduled or live status",
          "",
          "Winners receive coins based on the payout structure shown for that challenge.",
        ].join("\n"),
      },
      {
        q: "Are Walk Champ coins real money?",
        a: [
          "No. Walk Champ coins are virtual in-app items used in supported app features.",
          "",
          "Coins are not automatically equal to cash and generally cannot be withdrawn directly as money.",
          "",
          "Cash winnings and virtual coin balances are treated separately.",
        ].join("\n"),
      },
      {
        q: "Can I withdraw coins?",
        a: [
          "Walk Champ coins cannot be directly withdrawn as cash unless a future feature explicitly states otherwise.",
          "",
          "Coins can be used for supported features such as Coins Battles and other eligible in-app activities.",
        ].join("\n"),
      },
      {
        q: "What happens to my coins if a Coins Battle is cancelled?",
        a: [
          "When an eligible Coins Battle is cancelled before it begins, the entry coins should be restored according to the challenge’s cancellation rules and transaction status.",
          "",
          "Check your Wallet after the cancellation. Contact admin@miragaming.com if the balance does not update.",
        ].join("\n"),
      },
      {
        q: "How do Cash Prize Challenges work?",
        a: [
          "Eligible users pay the displayed cash entry amount.",
          "",
          "The entry contributions form the prize pool. Payment-processing and platform fees are charged separately when applicable and are displayed before confirmation.",
          "",
          "Participants compete using verified steps, and cash payouts are distributed according to the winner structure shown before registration.",
        ].join("\n"),
      },
      {
        q: "Is the entry amount the same as the total payment?",
        a: [
          "Not always.",
          "",
          "Your checkout may include:",
          "• Entry contribution",
          "• Payment-processing fee",
          "• Platform or service fee",
          "• Applicable tax or provider charges",
          "",
          "The complete total must be displayed before you confirm the payment.",
        ].join("\n"),
      },
      {
        q: "Are processing and platform fees deducted from the prize pool?",
        a: [
          "Under Walk Champ’s current model, the displayed entry contribution goes toward the prize pool.",
          "",
          "Processing and platform fees are charged separately when applicable.",
          "",
          "For example:",
          "100 participants × $3 entry contribution = $300 prize pool.",
          "",
          "Any additional processing or platform charges are shown separately during checkout.",
        ].join("\n"),
      },
      {
        q: "How is the cash prize pool calculated?",
        a: [
          "The prize pool is based on confirmed participant entry contributions.",
          "",
          "Example:",
          "• 100 participants",
          "• $3 entry contribution per participant",
          "• Prize pool: $300",
          "",
          "The displayed prize pool can grow as more users register.",
        ].join("\n"),
      },
      {
        q: "How many winners are selected?",
        a: [
          "The number of winners can change based on the final number of participants.",
          "",
          "Smaller races may have fewer winning positions. Larger races may reward more positions.",
          "",
          "The exact winner count, percentage split, estimated payout, and final prize pool should be displayed before registration and locked when the race begins.",
        ].join("\n"),
      },
      {
        q: "How are cash payouts divided?",
        a: [
          "Cash payouts follow the distribution shown for that challenge.",
          "",
          "For example, a large race may reward several top finishers, while a small race may reward only one, two, or three positions.",
          "",
          "Walk Champ applies the displayed percentages to the final prize pool and handles cent-level rounding automatically.",
        ].join("\n"),
      },
      {
        q: "When will I receive my cash prize?",
        a: [
          "Cash rewards are processed after:",
          "• The race ends",
          "• Results are validated",
          "• Suspicious activity reviews are completed",
          "• Eligibility is confirmed",
          "• Any required identity or payout verification is completed",
          "",
          "Exact transfer timing depends on the payout method, bank, country, and payment provider.",
        ].join("\n"),
      },
      {
        q: "Why are Cash Prize Challenges unavailable to me?",
        a: [
          "Possible reasons include:",
          "• Unsupported country",
          "• Unsupported US state",
          "• Age restriction",
          "• Location-verification failure",
          "• KYC requirement",
          "• Payment-provider limitation",
          "• Account restriction",
          "• Paid feature temporarily disabled in your region",
          "",
          "Free, Coins, Groups, and other features may still remain available.",
        ].join("\n"),
      },
      {
        q: "What is a Sponsored Event?",
        a: [
          "A Sponsored Event is a special challenge organized or funded by Walk Champ or an approved partner.",
          "",
          "Sponsored rewards may include:",
          "• Cash",
          "• Coins",
          "• Achievement badges",
          "• Titles",
          "• Physical prizes",
          "• Recognition",
          "• Event-specific benefits",
          "",
          "Each Sponsored Event displays its own entry requirement, participant capacity, goal, schedule, and reward rules.",
        ].join("\n"),
      },
      {
        q: "Can I register for more than one Sponsored Event?",
        a: [
          "A user can register for only one Sponsored Event at a time.",
          "",
          "To register for another Sponsored Event, you must either leave your current Sponsored Event or wait until it has been completed.",
        ].join("\n"),
      },
      {
        q: "Why can’t I join another Sponsored Event?",
        a: [
          "You already have an active or upcoming Sponsored Event registration.",
          "",
          "Leave the current Sponsored Event, where permitted, or wait until it has completed before registering for another one.",
        ].join("\n"),
      },
      {
        q: "What happens if I leave a Sponsored Event?",
        a: [
          "If the event uses the standard refundable pre-start entry rule, leaving before the event begins may restore the required coins.",
          "",
          "After the event starts, the entry may no longer be refundable.",
          "",
          "The exact rule shown on the event registration screen applies.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Creating Challenges",
    items: [
      {
        q: "Can I create my own challenge?",
        a: [
          "Yes. Where enabled, users can create public or private challenges.",
          "",
          "Depending on challenge type, you may select:",
          "• Free, Coins, or eligible Cash entry",
          "• Step goal",
          "• Start date and time",
          "• Duration",
          "• Public or private visibility",
          "• Country availability",
          "• Participant capacity",
          "• Race-track theme",
          "• Invite list or room code",
          "",
          "All challenge values must meet Walk Champ’s validation rules.",
        ].join("\n"),
      },
      {
        q: "Can I create a private challenge?",
        a: [
          "Yes. Private challenges can be created for invited friends, family members, coworkers, or other selected users.",
          "",
          "Private rooms may use direct invitations or a room code.",
          "",
          "Only users with the correct invitation or code can join.",
        ].join("\n"),
      },
      {
        q: "Can I create a future scheduled race?",
        a: [
          "Yes. Select a future start date and time during challenge creation.",
          "",
          "Once creation succeeds:",
          "• The room appears in Available Rooms.",
          "• The room count updates.",
          "• The race appears under Next Race.",
          "• A countdown is displayed.",
          "• Registered users can enter the Waiting Room.",
        ].join("\n"),
      },
      {
        q: "What happens if nobody joins my room?",
        a: [
          "Some challenge types require a minimum number of participants.",
          "",
          "If the minimum is not reached by the required start time, the room may be cancelled or closed. Refunds or restored balances depend on whether the challenge used Free, Coins, Cash, or Sponsored entry rules.",
        ].join("\n"),
      },
      {
        q: "Can a host cancel a future room?",
        a: [
          "Yes, before the race starts and when allowed by the challenge rules.",
          "",
          "When the host cancels:",
          "• Registered users are removed.",
          "• Applicable entries are refunded or restored.",
          "• The race is removed from Next Race.",
          "• The room is removed from Available Rooms.",
          "• Users may receive a notification.",
        ].join("\n"),
      },
      {
        q: "Can a host cancel a race after it starts?",
        a: [
          "A live race generally should not be cancelled directly by the host.",
          "",
          "Walk Champ support or administrative intervention may be required for serious technical, safety, or compliance issues.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Scheduled Races and Next Race",
    items: [
      {
        q: "What is the Next Race section?",
        a: [
          "Next Race shows future scheduled races for which you are already registered.",
          "",
          "It may include:",
          "• Free Challenges",
          "• Coins Battles",
          "• Cash Prize Challenges",
          "• Sponsored Events",
          "",
          "The cards are ordered by the nearest upcoming start time.",
        ].join("\n"),
      },
      {
        q: "Can Next Race show more than one race?",
        a: [
          "Yes. When multiple future registrations exist, the cards appear in a horizontally scrollable carousel.",
          "",
          "Each card displays:",
          "• Challenge type",
          "• Registered status",
          "• Countdown",
          "• Participant count",
          "• Step goal",
          "• Entry type",
          "• Prize or reward",
          "• Waiting Room action",
        ].join("\n"),
      },
      {
        q: "Why did my race disappear from Next Race?",
        a: [
          "Next Race displays future races only.",
          "",
          "When the countdown reaches zero, the card is removed from Next Race and the race becomes available through the Live tab.",
          "",
          "A cancelled, withdrawn, completed, or invalid registration will also be removed.",
        ].join("\n"),
      },
      {
        q: "Why is my newly created race not immediately showing?",
        a: [
          "The Walk tab should refresh automatically after successful creation.",
          "",
          "If it does not:",
          "• Return to Walk.",
          "• Pull to refresh if available.",
          "• Reopen the tab.",
          "• Check Available Rooms.",
          "• Confirm the challenge was successfully created.",
          "",
          "If the issue continues, contact admin@miragaming.com.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Waiting Room",
    items: [
      {
        q: "What is the Waiting Room?",
        a: [
          "The Waiting Room is the pre-race screen for a future scheduled challenge.",
          "",
          "It shows:",
          "• Scheduled start time",
          "• Participant slots",
          "• Host",
          "• Online or offline status",
          "• Step goal",
          "• Entry information",
          "• Prize pool or reward",
          "• Room ID",
          "• Leave or cancel options",
        ].join("\n"),
      },
      {
        q: "Do I need to stay in the Waiting Room?",
        a: [
          "No.",
          "",
          "You can leave the Waiting Room and continue using Walk Champ. The race starts automatically at the scheduled time.",
          "",
          "Enable push notifications so Walk Champ can alert you when the race begins.",
        ].join("\n"),
      },
      {
        q: "Who appears in the first participant slot?",
        a: [
          "The room host always appears in the first slot and is identified with a HOST badge.",
          "",
          "The remaining occupied slots show registered participants in registration order.",
        ].join("\n"),
      },
      {
        q: "What do the green and gray dots mean?",
        a: [
          "A green dot means the user is currently online.",
          "",
          "A gray dot means the user is currently offline or their current presence cannot be confirmed.",
          "",
          "Being offline does not remove a user’s registration.",
        ].join("\n"),
      },
      {
        q: "Why is someone’s profile image missing?",
        a: [
          "A placeholder or initials may appear when:",
          "• The user has no profile picture",
          "• The picture is still loading",
          "• The profile image URL is temporarily unavailable",
          "• The app is offline",
          "• Cached profile information needs refreshing",
          "",
          "Reopen or refresh the Waiting Room. Contact admin@miragaming.com if valid profile pictures consistently fail to load.",
        ].join("\n"),
      },
      {
        q: "What happens when the countdown reaches zero?",
        a: [
          "The scheduled race becomes live.",
          "",
          "The upcoming card is removed from Next Race, and participants can access the race through:",
          "• Live tab",
          "• My Races filter",
          "• Race notification",
          "• Existing live-race navigation",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Live Challenges",
    items: [
      {
        q: "What is the Live tab?",
        a: [
          "The Live tab shows races currently in progress and recently completed challenges.",
          "",
          "Filters may include:",
          "• All",
          "• My Races",
          "• Free",
          "• Coins Battle",
          "• Cash Challenges",
          "• Sponsored Events",
        ].join("\n"),
      },
      {
        q: "What does My Races show?",
        a: [
          "My Races displays live races where you are:",
          "• The host",
          "• A confirmed participant",
          "• Currently racing",
          "",
          "It does not include races where you are only watching as a spectator.",
        ].join("\n"),
      },
      {
        q: "What is the difference between View My Race and Watch Live?",
        a: [
          "View My Race opens the participant version of the race when you are actively competing.",
          "",
          "Watch Live opens spectator mode when you are not participating.",
          "",
          "View Results opens the final leaderboard after the race has completed.",
        ].join("\n"),
      },
      {
        q: "What happens after my race finishes?",
        a: [
          "Once results are available, the live action changes to View Results.",
          "",
          "Completed races may appear in:",
          "• Recently Finished",
          "• Race History",
          "• My Races results",
          "• Leaderboard or Results screen",
        ].join("\n"),
      },
      {
        q: "Why does the Race Track show only some participants?",
        a: [
          "The visual Race Track has a limited number of lanes for readability.",
          "",
          "For larger races, it may show:",
          "• Top-ranked racers",
          "• The current user",
          "• Nearby competitors",
          "• A selected group of visible participants",
          "",
          "The full race can still include more participants than the number of visible lanes.",
        ].join("\n"),
      },
      {
        q: "Where can I see all participants?",
        a: [
          "Open the Live Board inside the race.",
          "",
          "The Live Board displays the complete participant ranking, including racers who are not currently shown on the visual track.",
        ].join("\n"),
      },
      {
        q: "Can a race support up to 100 participants?",
        a: [
          "Where enabled, a race can support more users than the ten visible track lanes.",
          "",
          "The Race Track remains a focused visual experience, while the Live Board contains the full ranking for all participants.",
        ].join("\n"),
      },
      {
        q: "How does live chat work?",
        a: [
          "Users may send supported messages, cheers, and reactions during a race.",
          "",
          "Live chat must follow Walk Champ’s community guidelines. Harassment, spam, offensive material, and misuse can be reported and may lead to restrictions.",
        ].join("\n"),
      },
      {
        q: "How does voice chat work?",
        a: [
          "Where voice is enabled, users must grant microphone permission.",
          "",
          "Individual mute controls affect the selected user’s local audio experience and should not mute the entire room.",
          "",
          "Voice access may also depend on the event and user permissions.",
        ].join("\n"),
      },
      {
        q: "Can spectators watch a race?",
        a: [
          "Yes, where spectator access is enabled.",
          "",
          "Spectators may view the Race Track, Live Board, participant progress, and supported chat without being counted as race participants.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Goals, Rankings, and Winners",
    items: [
      {
        q: "How are rankings calculated?",
        a: [
          "Rankings use valid race steps recorded during the eligible race period.",
          "",
          "Depending on the challenge, ordering may be based on:",
          "• Current eligible steps",
          "• Percentage of goal completed",
          "• Verified goal-completion time",
          "• Final result rules",
          "• Tie-break configuration",
        ].join("\n"),
      },
      {
        q: "How is the winner determined?",
        a: [
          "For goal-based races, the user who reaches the required goal first using valid verified records may be ranked first.",
          "",
          "Walk Champ records the most precise eligible completion timestamp available.",
          "",
          "Final results may be reviewed before rewards are released.",
        ].join("\n"),
      },
      {
        q: "What happens if two users finish at the same time?",
        a: [
          "Walk Champ compares precise verified completion timestamps.",
          "",
          "If the timestamps are exactly identical, the challenge’s configured tie-break rule is applied.",
        ].join("\n"),
      },
      {
        q: "What happens if no participant reaches the goal?",
        a: [
          "The outcome follows the rules displayed before registration.",
          "",
          "Depending on the challenge, Walk Champ may:",
          "• Use final step ranking",
          "• Apply a no-winner policy",
          "• Refund eligible entries",
          "• Resolve rewards according to the event configuration",
          "• Require administrative review",
        ].join("\n"),
      },
      {
        q: "Are results immediately final?",
        a: [
          "Not always.",
          "",
          "Results may remain provisional while Walk Champ verifies:",
          "• Eligible steps",
          "• Completion timestamps",
          "• Withdrawals",
          "• Forfeitures",
          "• Disqualifications",
          "• Payment status",
          "• Suspicious activity",
          "",
          "Rewards are released after the required validation is completed.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Groups and Social Features",
    items: [
      {
        q: "What are Walk Champ Groups?",
        a: [
          "Groups let users compete and stay connected with:",
          "• Friends",
          "• Family",
          "• Offices",
          "• Custom communities",
          "",
          "A group can have its own name, theme, member list, daily goal, leaderboard, and progress view.",
        ].join("\n"),
      },
      {
        q: "What can group administrators do?",
        a: [
          "Depending on permissions, a group administrator may:",
          "• Manage members",
          "• Update the group",
          "• Choose the group theme",
          "• View group progress",
          "• Moderate activity",
          "• Share group information",
          "",
          "Administrator capabilities depend on the current group implementation.",
        ].join("\n"),
      },
      {
        q: "Can I create a custom group?",
        a: [
          "Yes. Select the Custom group type and choose the supported settings, including the group’s color theme.",
          "",
          "Available themes may include:",
          "• Purple Blue",
          "• Cyan Green",
          "• Pink Orange",
          "• Gold Amber",
          "• Red Rose",
          "• Teal Mint",
        ].join("\n"),
      },
      {
        q: "Can other users view my profile?",
        a: [
          "Users can open a limited public profile where supported.",
          "",
          "A public profile may show:",
          "• Username",
          "• Avatar",
          "• Country",
          "• Equipped title",
          "• Lifetime steps",
          "• Coin balance",
          "• Races played",
          "• Race wins",
          "• Current streak",
          "",
          "Private account, payment, health, and group information should not be exposed.",
        ].join("\n"),
      },
      {
        q: "What are achievements and titles?",
        a: [
          "Achievements recognize milestones involving:",
          "• Walking",
          "• Streaks",
          "• Races",
          "• Leaderboards",
          "• Groups",
          "• Sponsored Events",
          "• Coins",
          "",
          "You can equip one unlocked title and display it on your profile, leaderboard rows, and supported race screens.",
        ].join("\n"),
      },
      {
        q: "How do friend requests work?",
        a: [
          "Users can send, receive, accept, or decline friend requests through supported social screens.",
          "",
          "Accepted friends may appear in chat, groups, invitations, public profiles, and activity notifications.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Referrals and Invite Friends",
    items: [
      {
        q: "How do I invite friends?",
        a: [
          "Open My Profile and tap Invite Friends.",
          "",
          "The Invite Friends screen displays your referral code, invite link, referral progress, and reward details.",
          "",
          "Tap Share Invite to open the native sharing options.",
        ].join("\n"),
      },
      {
        q: "How do I copy my referral code?",
        a: [
          "Tap the displayed invite code or copy icon.",
          "",
          "Walk Champ copies the code to your clipboard and shows a confirmation message.",
        ].join("\n"),
      },
      {
        q: "When do referral rewards apply?",
        a: [
          "Referral rewards depend on the current program configuration.",
          "",
          "A friend may need to:",
          "• Create an account using your code",
          "• Complete account verification",
          "• Join an eligible challenge",
          "• Complete the required qualifying activity",
          "• Satisfy fraud and eligibility checks",
          "",
          "The Invite Friends screen should display the applicable conditions.",
        ].join("\n"),
      },
      {
        q: "Why has my referral reward not appeared?",
        a: [
          "Possible reasons include:",
          "• The friend did not use your referral code",
          "• The friend has not completed the qualifying requirement",
          "• Verification is still pending",
          "• The referral was found to be ineligible",
          "• The reward is still processing",
          "",
          "Contact admin@miragaming.com with both usernames if you need help.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Notifications and Settings",
    items: [
      {
        q: "How do I enable race notifications?",
        a: [
          "Open My Profile and enable Push Notifications.",
          "",
          "You may also need to allow notifications in your phone’s system settings.",
          "",
          "Notifications can include:",
          "• Race starting",
          "• Waiting Room updates",
          "• Invitations",
          "• Friend activity",
          "• Goal completion",
          "• Results",
          "• Wallet updates",
        ].join("\n"),
      },
      {
        q: "Why did I not receive a race-start notification?",
        a: [
          "Check that:",
          "• Push Notifications are enabled in Walk Champ",
          "• System notifications are enabled",
          "• Battery optimization is not blocking background activity",
          "• Your device has internet access",
          "• You remain registered for the race",
        ].join("\n"),
      },
      {
        q: "What does the vibration setting control?",
        a: "The vibration setting controls supported haptic feedback within Walk Champ, such as button interactions, race events, alerts, and other in-app actions.",
      },
      {
        q: "Can I use dark mode?",
        a: [
          "Yes. Dark mode can be enabled from My Profile when supported.",
          "",
          "Walk Champ’s primary design is optimized for a premium dark experience.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Coins, Cash Wallet, and Payments",
    items: [
      {
        q: "What is the Walk Champ Wallet?",
        a: [
          "The Wallet manages supported balances and transaction information, which may include:",
          "• Cash winnings",
          "• Refunds",
          "• Promotional credits",
          "• Walk Champ coins",
          "• Purchases",
          "• Withdrawals",
          "• Pending transactions",
          "",
          "Cash, credits, and coins may have different rules and must be displayed separately.",
        ].join("\n"),
      },
      {
        q: "Can I use my wallet balance to enter another challenge?",
        a: [
          "Eligible wallet cash or credits may be applied to another challenge when this option is supported at checkout.",
          "",
          "Walk Champ coins can be used only for supported coin-based features.",
        ].join("\n"),
      },
      {
        q: "How do I withdraw cash winnings?",
        a: [
          "Open Wallet and select the available withdrawal option.",
          "",
          "You may be required to:",
          "• Verify your identity",
          "• Add payout details",
          "• Select a supported method",
          "• Meet the minimum withdrawal amount",
          "• Complete compliance checks",
          "",
          "Available payout methods vary by country.",
        ].join("\n"),
      },
      {
        q: "Why is my withdrawal pending?",
        a: [
          "Common reasons include:",
          "• Race results not yet finalized",
          "• Identity verification",
          "• Compliance review",
          "• Bank processing",
          "• Payout-provider processing",
          "• Incorrect payout details",
          "• Minimum withdrawal requirement",
          "• Fraud or security review",
        ].join("\n"),
      },
      {
        q: "Are there withdrawal fees?",
        a: [
          "Any Walk Champ fee should be shown before confirmation.",
          "",
          "Banks, payment processors, currency-conversion providers, or payout services may charge their own fees depending on the country, currency, and method.",
        ].join("\n"),
      },
      {
        q: "Do I have to pay taxes on winnings?",
        a: [
          "Challenge winnings may be taxable depending on your location.",
          "",
          "Walk Champ does not provide tax advice. Users are responsible for maintaining records and consulting a qualified tax professional when necessary.",
        ].join("\n"),
      },
      {
        q: "What happens to my balance if I delete my account?",
        a: [
          "Withdraw any eligible cash balance before deleting your account.",
          "",
          "Pending financial transactions may delay account deletion. Walk Champ may retain certain payment, security, fraud-prevention, or compliance records as required by law.",
          "",
          "Contact admin@miragaming.com for balance-related assistance.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Refunds, Withdrawals, and Cancellations",
    items: [
      {
        q: "Can I get a refund after joining a challenge?",
        a: [
          "Refund eligibility depends on:",
          "• Challenge type",
          "• Entry type",
          "• Whether the race has started",
          "• Withdrawal timing",
          "• Payment status",
          "• Rules accepted during registration",
          "",
          "Voluntarily forfeiting after a race begins is generally not refundable.",
          "",
          "Duplicate charges, verified technical errors, and exceptional cases may be reviewed.",
        ].join("\n"),
      },
      {
        q: "What happens if Walk Champ cancels a challenge?",
        a: [
          "Applicable entry amounts, coins, or credits are returned according to the original challenge and payment rules.",
          "",
          "Refund timing can vary by payment provider.",
        ].join("\n"),
      },
      {
        q: "What happens if I withdraw from a scheduled room?",
        a: [
          "Before the race starts, the app may allow you to withdraw.",
          "",
          "Applicable refunds depend on the challenge:",
          "• Free: no entry refund required",
          "• Coins: eligible coins may be restored",
          "• Cash: refund follows the displayed cancellation terms",
          "• Sponsored: the configured pre-start refund rule applies",
          "",
          "After the race starts, leaving may be treated as a forfeit.",
        ].join("\n"),
      },
      {
        q: "What should I do if I was charged incorrectly?",
        a: [
          "Contact admin@miragaming.com and provide:",
          "• Walk Champ username",
          "• Account email",
          "• Transaction date",
          "• Amount",
          "• Challenge or room ID",
          "• Receipt or screenshot",
          "• Payment-provider reference",
          "",
          "Never send your complete card number, password, or security code.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Fair Play and Community",
    items: [
      {
        q: "How does Walk Champ prevent cheating?",
        a: [
          "Walk Champ may use:",
          "• Verified health-platform data",
          "• Manual-entry exclusion",
          "• Device and source checks",
          "• Step-pattern validation",
          "• Suspicious-activity detection",
          "• Account review",
          "• Completion-timestamp verification",
          "",
          "Detailed fraud-detection thresholds are not publicly disclosed.",
        ].join("\n"),
      },
      {
        q: "What activity is prohibited?",
        a: [
          "Prohibited activity includes:",
          "• Manually adding or altering steps",
          "• Using scripts or automation",
          "• Using modified devices or emulators",
          "• Sharing accounts",
          "• Falsifying location",
          "• Manipulating health records",
          "• Fraudulent payments",
          "• Coordinating unfair results",
          "• Harassment or threats",
          "• Spam or impersonation",
          "• Posting another person’s private information",
        ].join("\n"),
      },
      {
        q: "What happens if a user cheats?",
        a: [
          "Depending on severity, Walk Champ may:",
          "• Remove invalid steps",
          "• Disqualify the user",
          "• Remove the user from a race",
          "• Forfeit rewards",
          "• Deny refunds",
          "• Suspend the account",
          "• Permanently close the account",
          "• Review or reverse affected payouts where legally permitted",
        ].join("\n"),
      },
      {
        q: "What are the Walk Champ community guidelines?",
        a: [
          "Walk Champ users should:",
          "• Treat others respectfully",
          "• Avoid harassment, threats, discrimination, and body-shaming",
          "• Keep chats free from spam",
          "• Never falsify activity",
          "• Protect other users’ personal information",
          "• Use voice and group features responsibly",
          "• Report unsafe or abusive behavior",
          "• Encourage other participants positively",
          "",
          "Serious issues can be reported to admin@miragaming.com.",
        ].join("\n"),
      },
      {
        q: "How do I report another user?",
        a: [
          "Use the available report option in the user’s public profile, chat, race, or group screen.",
          "",
          "Include:",
          "• Username",
          "• Race or group",
          "• Description",
          "• Date and approximate time",
          "• Screenshots when available",
          "",
          "Do not publicly repost the person’s private information.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Availability, Location, and Legal",
    items: [
      {
        q: "Where is Walk Champ available?",
        a: [
          "General features may be available in supported countries.",
          "",
          "Free Challenges, Coins, Groups, and Sponsored features may have broader availability than cash competitions.",
          "",
          "Cash Prize Challenges and payouts are controlled by country, state, payment-provider coverage, age, and legal eligibility.",
        ].join("\n"),
      },
      {
        q: "What happens if paid challenges become unavailable in my region?",
        a: [
          "You may lose access to new paid registrations while other app features remain available.",
          "",
          "Existing balances and eligible pending payouts continue to be handled according to their applicable terms.",
          "",
          "Contact admin@miragaming.com if your payout is affected.",
        ].join("\n"),
      },
      {
        q: "Can I use Walk Champ while traveling?",
        a: [
          "General app access may continue while traveling.",
          "",
          "However:",
          "• Cash feature eligibility may depend on your current location.",
          "• Your timezone may update.",
          "• Some paid features may be temporarily unavailable.",
          "• Scheduled times should be reviewed after location changes.",
        ].join("\n"),
      },
      {
        q: "Why does Walk Champ request location permission?",
        a: [
          "Walk Champ may use location to:",
          "• Determine your timezone",
          "• Display scheduled times correctly",
          "• Verify regional eligibility",
          "• Apply country or state restrictions",
          "• Support fraud prevention and compliance",
          "",
          "Location use is governed by Walk Champ’s Privacy Policy.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Account and Privacy",
    items: [
      {
        q: "How do I update my profile?",
        a: [
          "Open My Profile and tap the edit icon.",
          "",
          "You can update supported fields such as:",
          "• Username",
          "• Avatar",
          "• Country",
          "• Other public profile details",
          "",
          "Save the changes when finished.",
        ].join("\n"),
      },
      {
        q: "How do I delete my account?",
        a: [
          "Open My Profile and tap Delete Account.",
          "",
          "Review the warning carefully and confirm the deletion request.",
          "",
          "Before deleting:",
          "• Withdraw eligible balances",
          "• Resolve pending transactions",
          "• Leave or complete active races where required",
          "• Save any information you need",
        ].join("\n"),
      },
      {
        q: "How does Walk Champ protect my privacy?",
        a: [
          "Walk Champ uses data to operate the app, verify steps, administer races, process payments, deliver notifications, prevent fraud, and provide support.",
          "",
          "Public profiles show only approved public information. Health, payment, authentication, and private group details should not be publicly exposed.",
          "",
          "Review Privacy Policy for complete information.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Troubleshooting",
    items: [
      {
        q: "Why is a screen showing old information?",
        a: [
          "Try:",
          "• Pulling to refresh",
          "• Changing tabs and returning",
          "• Reopening the screen",
          "• Checking your internet connection",
          "• Restarting Walk Champ",
          "• Updating the app",
          "",
          "Walk Champ should refresh room counts, Next Race cards, registrations, and live states after successful actions.",
        ].join("\n"),
      },
      {
        q: "Why does a race count update only after I reopen a screen?",
        a: [
          "This may indicate a temporary cache or synchronization delay.",
          "",
          "The app should invalidate and refresh relevant challenge data after:",
          "• Creating a room",
          "• Registering",
          "• Withdrawing",
          "• Cancelling",
          "• Joining",
          "• Completing a race",
          "",
          "Report repeatable cases to admin@miragaming.com.",
        ].join("\n"),
      },
      {
        q: "Why is a registered participant missing from the Waiting Room?",
        a: [
          "Possible causes include:",
          "• Participant data is still loading",
          "• The registration was not completed",
          "• The participant withdrew",
          "• The screen needs refreshing",
          "• A synchronization issue occurred",
          "",
          "The host should always appear first, followed by confirmed participants.",
        ].join("\n"),
      },
      {
        q: "Why can’t I open the Race Track?",
        a: [
          "Confirm that:",
          "• The race is live",
          "• You are still registered",
          "• You have internet access",
          "• Step permissions are enabled",
          "• The app is updated",
          "• The race has not ended or been cancelled",
          "",
          "Use View My Race from the Live tab when you are participating.",
        ].join("\n"),
      },
      {
        q: "Why can’t I see a completed race?",
        a: [
          "Look under:",
          "• Recently Finished",
          "• My Races",
          "• Race History",
          "• Results",
          "• Leaderboards",
          "",
          "Final results may take time while verification is completed.",
        ].join("\n"),
      },
    ],
  },
  {
    title: "Support",
    items: [
      {
        q: "How do I contact Walk Champ support?",
        a: [
          "Email: admin@miragaming.com",
          "",
          "Include:",
          "• Walk Champ username",
          "• Account email",
          "• Device model",
          "• Android or iOS version",
          "• Walk Champ app version",
          "• Description of the issue",
          "• Race or room ID",
          "• Approximate date and time",
          "• Screenshots or screen recording",
          "",
          "Do not send passwords, complete card details, or security codes.",
        ].join("\n"),
      },
      {
        q: "Still need help?",
        a: [
          "Contact the Walk Champ support team at admin@miragaming.com.",
          "",
          "Suggested subject: Walk Champ Support Request",
          "",
          "Include your username, device information, and a clear description of the issue so the support team can assist you faster.",
        ].join("\n"),
      },
    ],
  },
];

export const WALK_CHAMP_FAQ_SUPPORT_EMAIL = "admin@miragaming.com";
